{
  pkgs,
  lib,
  ...
}: {
  users.users = {
    # your username
    nixos = {
      ## You can set an initial password for your user.
      ## If you do, you can skip setting a root password by passing '--no-root-passwd' to nixos-install.
      ## Be sure to change it (using passwd) after rebooting!
      # initialPassword = "correcthorsebatterystaple";
      isNormalUser = true;

      # generated by `mkpasswd`
      hashedPassword = "***REMOVED***";
      ## Be sure to add any other groups you need (such as networkmanager, audio, docker, etc)
      extraGroups = ["wheel"];
      linger = true;
      shell = pkgs.fish;
    };
  };

  security.sudo = {
    execWheelOnly = true;
    # wheelNeedsPassword = lib.mkForce true;
    configFile = ''
      Defaults:nixos  timestamp_timeout=5
    '';
  };
}
